name: Run Weather Script

on:
  schedule:
    # Runs at 10 AM UTC
    - cron: '0 10 * * *'
  workflow_dispatch:  # Allows manual trigger event to test the workflow

jobs:
  run-weather-script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu virtual machine

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Ensure weather.sh is executable and run it
    - name: Run weather.sh script
      run: |
        chmod +x weather.sh
        ./weather.sh

    # Step 3: Commit and push changes if any
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Stage only if there are changes
        git add .
        git commit -m "Update weather data" ||
        echo "No changes to commit"
        git push
        